POST http://localhost/credentials/register 
Content-Type: application/json

{
    "email": "test@gmail.com" , 
    "firstName": "Diego",
    "lastName": "López",
    "password": "12345",
    "signature": "test",
    "enterprise_account": true
}

###

POST http://localhost/credentials/login 
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"12345"
}



###
POST http://localhost/personal-budget/create
Content-Type: application/json

{
    "budget_name": "Servicios 2",
    "owner_id": "dTorresv2020",
    "income": {
        "amount": 120000,
        "type": "ANNUAL"
    }
}

//Update
###
PUT  http://localhost/personal-budget/update/160743844711
Content-Type: application/json

{
    "budget_name": "Servicios Torres",
    "income": {
        "amount": 10500,
        "type": "MONTHLY"
    }
}


//budgetDeleter
###
DELETE http://localhost/personal-budget/delete/160743585835
Content-Type: application/json


//Idfinder
###
GET http://localhost/personal-budget/get/all/dTorresv2020


//Crear cargo
###
POST http://localhost/personal-budget/create/charge/160743844711
Content-Type: application/json

{
        "title": "Luz",
        "amount": 3000   
}

//Eliminar cargo
###
DELETE http://localhost/personal-budget/delete/charge/160743567740


//BudgetFinder
###
GET http://localhost/personal-budget/get/160743844711