POST http://localhost/credentials/register 
Content-Type: application/json

{
    "email": "test@gmail.com" , 
    "firstName": "Diego",
    "lastName": "López",
    "password": "12345",
    "signature": "test",
    "enterprise_account": true
}

###

POST http://localhost/credentials/login 
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"12345"
}

###
POST http://localhost/enterprise-budget/create
Content-Type: application/json

{
    "budget_name": "Comida",
    "owner_id": "dlopezp",
    "budget_limit": 2500
}

###
PUT  http://localhost/enterprise-budget/update/160728290348
Content-Type: application/json

{
    "budget_name": "Publicidad",
    "budget_limit": 3000
}

###
DELETE http://localhost/enterprise-budget/delete/160728278280
Content-Type: application/json

###
POST http://localhost/enterprise-budget/collaborator/add/160728294158
Content-Type: application/json

{
    "collaborator_id": "dtorres",
    "collaborator_name": "Juan Daniel Torres Vera",
    "budget_percentage": 10
}

###

DELETE http://localhost/enterprise-budget/remove/160728294158/dtorres


###

GET http://localhost/enterprise-budget/get/all/dlopezp


###
GET http://localhost/enterprise-budget/get/shared/all/dtorres


###
GET http://localhost/enterprise-budget/get/160728278280

###
POST http://localhost/enterprise-budget/create/charge/160728278280
Content-Type: application/json

{
        "collaborator_id": "dtorres",
        "title": "Pago de agua",
        "amount": 1000   
}

###
DELETE http://localhost/enterprise-budget/delete/charge/160728402159